// Compiles content/ into data/content.js for the browser, and writes the narration script for tools/narrate.py.
// Usage: node tools/build-content.mjs
import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const read = (p) => JSON.parse(fs.readFileSync(path.join(root, p), 'utf8'));
const readOpt = (p, d) => (fs.existsSync(path.join(root, p)) ? read(p) : d);

const ACTS = [
  { id: 'prologue', label: 'Prologue', title: 'The Longest Age' },
  { id: 'roots', label: 'Act I', title: 'Roots' },
  { id: 'toolmakers', label: 'Act II', title: 'The First Toolmakers' },
  { id: 'many-humans', label: 'Act III', title: 'Many Ways of Being Human' },
  { id: 'one-species', label: 'Act IV', title: 'One Species, Every Continent' },
  { id: 'warming', label: 'Act V', title: 'After the Ice' },
  { id: 'transition', label: 'Act VI', title: 'Sowing and Herding' },
  { id: 'metal', label: 'Act VII', title: 'Toward Metal' },
];

// Split narration paragraphs into sentences. Decimal points and a few abbreviations are protected.
const ABBR = /\b(?:Mr|Mrs|Ms|Dr|St|Mt|vs|approx|H|A|P|Au|Ar|No)\.$/;
function sentences(par) {
  const out = [];
  let buf = '';
  const re = /([.!?…][”’)]?)\s+/g;
  let last = 0, m;
  const pieces = [];
  while ((m = re.exec(par))) { pieces.push(par.slice(last, m.index + m[1].length)); last = m.index + m[0].length; }
  pieces.push(par.slice(last));
  for (const p of pieces) {
    buf = buf ? `${buf} ${p}` : p;
    if (ABBR.test(buf.trim())) continue;
    if (buf.trim()) out.push(buf.trim());
    buf = '';
  }
  if (buf.trim()) out.push(buf.trim());
  return out;
}

const dir = path.join(root, 'content/chapters');
const files = fs.readdirSync(dir).filter((f) => f.endsWith('.json')).sort();
const chapters = files.map((f) => read(`content/chapters/${f}`)).sort((a, b) => a.order - b.order);

const sites = new Map();
let sourceCount = 0;
const out = chapters.map((c) => {
  for (const s of c.sites) {
    if (!sites.has(s.id)) sites.set(s.id, { ...s, chapters: [c.id] });
    else {
      const e = sites.get(s.id);
      e.chapters.push(c.id);
      // Keep the widest time range and the longer summary
      e.start = Math.max(e.start, s.start);
      e.end = Math.min(e.end, s.end);
      if ((s.summary || '').length > (e.summary || '').length) { e.summary = s.summary; e.dateLabel = s.dateLabel || e.dateLabel; }
    }
  }
  sourceCount += c.sources.length;
  const paragraphs = c.narration.map(sentences);
  return {
    id: c.id, order: c.order, act: c.act, title: c.title, subtitle: c.subtitle, era: c.era,
    start: c.start, end: c.end, dateLabel: c.dateLabel, regions: c.regions, focus: c.focus, emblem: c.emblem,
    summary: c.summary, paragraphs, sentences: paragraphs.flat(), pronounce: c.pronounce || {},
    body: c.body, debates: c.debates, keyFacts: c.keyFacts, siteIds: [...new Set(c.sites.map((s) => s.id))],
    routes: c.routes || [], themes: c.themes, sources: c.sources,
  };
});

const species = readOpt('content/species.json', { species: [], geneFlow: [] });
const glossary = readOpt('content/glossary.json', { terms: [] });
const methods = readOpt('content/methods.json', { methods: [] });

const data = {
  acts: ACTS,
  chapters: out,
  sites: [...sites.values()].sort((a, b) => b.start - a.start),
  species: species.species || [],
  geneFlow: species.geneFlow || [],
  glossary: (glossary.terms || []).sort((a, b) => a.term.localeCompare(b.term)),
  methods: methods.methods || [],
  stats: { sources: sourceCount },
};
fs.writeFileSync(path.join(root, 'data/content.js'), `// Generated by tools/build-content.mjs from content/. Do not edit by hand.\nwindow.LD_CONTENT=${JSON.stringify(data)};\n`);

// Narration script for the speech engine
fs.mkdirSync(path.join(root, 'tools/raw'), { recursive: true });
fs.writeFileSync(path.join(root, 'tools/raw/narration-script.json'), JSON.stringify(out.map((c) => ({ id: c.id, sentences: c.sentences, paragraphs: c.paragraphs.map((p) => p.length), pronounce: c.pronounce })), null, 1));

const words = out.reduce((a, c) => a + c.sentences.join(' ').split(/\s+/).length, 0);
const bodyWords = out.reduce((a, c) => a + c.body.flatMap((s) => s.paragraphs).join(' ').split(/\s+/).length, 0);
console.log(`${out.length} chapters, ${data.sites.length} sites, ${sourceCount} references, ${data.species.length} species, ${data.glossary.length} glossary terms, ${data.methods.length} methods`);
console.log(`narration ${words} words (about ${Math.round(words / 150)} minutes), body ${bodyWords} words`);
