"""Render the documentary series to MP3 with Kokoro: one file per scene, several voices, and cue and sentence timings.

Usage:
    node tools/build-series.mjs                     # writes tools/raw/series-script.json
    python tools/narrate-series.py [episode-id ...] # render the scenes whose text or voices changed
    python tools/narrate-series.py --audition       # one short clip per candidate voice (audio/series/voices/)
    python tools/narrate-series.py --check          # print the phonemes of every sentence that uses the lexicon

Output: audio/series/<episode>/<scene>.mp3 and data/series-audio.js (window.LD_SERIES_AUDIO), keyed by episode and
scene: file, duration and, per cue, start and end plus the start and end of each sentence, all in seconds.
The speaker of each cue picks the voice and the phonemizer language (British voices use en-gb) from series.json.
Pronunciations for hard names come from tools/lexicon.json, as for the chapters (see tools/narrate.py).
"""
import hashlib
import json
import os
import sys
import time

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import narrate  # noqa: E402  (shares the lexicon, phonemizer, trimming and MP3 encoding)

ROOT = narrate.ROOT
RAW = narrate.RAW
SR = narrate.SR
SPEED = float(os.environ.get('NARRATOR_SPEED', '0.96'))
PAUSE_SENTENCE = 0.42
PAUSE_CUE = 0.7          # between two cues of the same speaker
PAUSE_SPEAKER = 0.85     # when the voice changes
TAIL = 0.6
BITRATE = 48             # kbit/s, mono speech
OUT_JS = os.path.join(ROOT, 'data', 'series-audio.js')


def load_existing():
    if not os.path.exists(OUT_JS):
        return {}
    txt = open(OUT_JS, encoding='utf-8').read()
    start = txt.find('window.LD_SERIES_AUDIO=') + len('window.LD_SERIES_AUDIO=')
    end = txt.find(';\n', start)
    try:
        return json.loads(txt[start:end])
    except ValueError:
        return {}


def write(manifest):
    with open(OUT_JS, 'w', encoding='utf-8') as f:
        f.write('// Generated by tools/narrate-series.py. Cue and sentence timings in seconds for audio/series/<episode>/<scene>.mp3.\n')
        f.write('window.LD_SERIES_AUDIO=' + json.dumps(manifest, ensure_ascii=False, separators=(',', ':')) + ';\n')


def encode(samples, path):
    import lameenc
    enc = lameenc.Encoder()
    enc.set_bit_rate(BITRATE)
    enc.set_in_sample_rate(SR)
    enc.set_channels(1)
    enc.set_quality(2)
    pcm = (np.clip(samples, -1, 1) * 32767).astype('<i2').tobytes()
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'wb') as f:
        f.write(enc.encode(pcm) + enc.flush())


def normalise(chunks, tail=TAIL):
    audio = np.concatenate(chunks + [np.zeros(int(tail * SR), dtype=np.float32)])
    peak = float(np.max(np.abs(audio))) or 1.0
    return audio * (0.89 / peak)


def main():
    from kokoro_onnx import Kokoro
    model = os.environ.get('KOKORO_MODEL', os.path.join(RAW, 'kokoro-v1.0.onnx'))
    voices = os.environ.get('KOKORO_VOICES', os.path.join(RAW, 'voices-v1.0.bin'))
    kokoro = Kokoro(model, voices)
    lexicon = narrate.load_lexicon()
    phonemize = narrate.Phonemizer(kokoro.tokenizer, lexicon)
    with open(os.path.join(RAW, 'series-script.json'), encoding='utf-8') as f:
        script = json.load(f)

    if '--check' in sys.argv:
        for sc in script['scenes']:
            for cue in sc['cues']:
                for s in cue['sentences']:
                    if phonemize.pattern.search(s):
                        print(f"{sc['episode']}/{sc['scene']} [{cue['voice']}]: {s}\n    {phonemize(s, cue['lang'])}")
        return

    manifest = load_existing()

    if '--audition' in sys.argv:
        aud = script.get('audition')
        if not aud:
            raise SystemExit('series.json has no audition block')
        files = manifest.setdefault('_voices', {})
        for voice in aud['voices']:
            lang = 'en-gb' if voice.startswith('b') else 'en-us'
            digest = hashlib.sha1(json.dumps([aud['text'], voice, SPEED], ensure_ascii=False).encode()).hexdigest()[:12]
            rel = f'audio/series/voices/{voice}.mp3'
            if files.get(voice, {}).get('hash') == digest and os.path.exists(os.path.join(ROOT, rel)):
                continue
            chunks = []
            for i, s in enumerate(narrate_sentences(aud['text'])):
                samples, sr = kokoro.create(phonemize(s, lang), voice=voice, speed=SPEED, is_phonemes=True)
                chunks.append(narrate.trim(np.asarray(samples, dtype=np.float32)))
                chunks.append(np.zeros(int(PAUSE_SENTENCE * SR), dtype=np.float32))
            audio = normalise(chunks, 0.3)
            encode(audio, os.path.join(ROOT, rel))
            files[voice] = {'file': rel, 'duration': round(len(audio) / SR, 2), 'hash': digest}
            print(f'{voice}: {len(audio) / SR:.1f}s', flush=True)
            write(manifest)
        write(manifest)
        return

    only = set(a for a in sys.argv[1:] if not a.startswith('--'))
    for sc in script['scenes']:
        ep, sid = sc['episode'], sc['scene']
        if only and ep not in only and f'{ep}/{sid}' not in only:
            continue
        digest = hashlib.sha1(json.dumps([sc['cues'], SPEED, sorted(lexicon.items())], ensure_ascii=False).encode()).hexdigest()[:12]
        rel = f'audio/series/{ep}/{sid}.mp3'
        prev = manifest.get(ep, {}).get(sid)
        if prev and prev.get('hash') == digest and os.path.exists(os.path.join(ROOT, rel)):
            continue
        t0 = time.time()
        chunks, cues, pos = [], [], 0.0
        last_voice = None
        for ci, cue in enumerate(sc['cues']):
            if ci:
                gap = PAUSE_SPEAKER if cue['voice'] != last_voice else PAUSE_CUE
                chunks.append(np.zeros(int(gap * SR), dtype=np.float32))
                pos += gap
            entry = {'start': round(pos, 2), 'sentences': []}
            for i, s in enumerate(cue['sentences']):
                samples, sr = kokoro.create(phonemize(s, cue['lang']), voice=cue['voice'], speed=SPEED, is_phonemes=True)
                assert sr == SR
                samples = narrate.trim(np.asarray(samples, dtype=np.float32))
                start = pos
                chunks.append(samples)
                pos += len(samples) / SR
                entry['sentences'].append([round(start, 2), round(pos, 2)])
                if i < len(cue['sentences']) - 1:
                    chunks.append(np.zeros(int(PAUSE_SENTENCE * SR), dtype=np.float32))
                    pos += PAUSE_SENTENCE
            entry['end'] = round(pos, 2)
            cues.append(entry)
            last_voice = cue['voice']
        audio = normalise(chunks)
        encode(audio, os.path.join(ROOT, rel))
        manifest.setdefault(ep, {})[sid] = {'file': rel, 'duration': round(len(audio) / SR, 2), 'cues': cues, 'hash': digest}
        n = sum(len(c['sentences']) for c in sc['cues'])
        print(f'{ep}/{sid}: {len(sc["cues"])} cues, {n} sentences, {len(audio) / SR:.0f}s audio in {time.time() - t0:.0f}s', flush=True)
        write(manifest)
    write(manifest)


def narrate_sentences(text):
    import re
    return [s for s in re.split(r'(?<=[.!?])\s+', text.strip()) if s]


if __name__ == '__main__':
    main()
